# Generated by Django 5.0.9 on 2024-11-09 09:19

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.IntegerField(unique=True)),
                ('uuid', models.CharField(default=main.models.node_uuid, max_length=50, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('weight', models.FloatField(default=1.0)),
                ('properties', models.CharField(max_length=50, null=True)),
                ('tag', models.CharField(default='', max_length=50)),
                ('ipv4', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('ipv6', models.GenericIPAddressField(null=True, protocol='IPv6')),
                ('port', models.IntegerField(default=4430, null=True)),
                ('idc', models.TextField(default='Unknown', max_length=2048, null=True)),
                ('remarks', models.TextField(max_length=2048, null=True)),
                ('upload', models.BigIntegerField(default=0)),
                ('download', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Push',
            fields=[
                ('push_id', models.AutoField(primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('lines', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mix_source', to='main.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mix_target', to='main.node')),
            ],
        ),
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('probe_result', models.IntegerField()),
                ('ts', models.IntegerField(default=main.models.current_unix)),
            ],
            options={
                'indexes': [models.Index(fields=['ts'], name='main_probe_ts_d18c86_idx')],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('ts', models.IntegerField(default=main.models.current_unix)),
                ('email_header', models.TextField(max_length=4096)),
                ('receiver', models.EmailField(max_length=50, null=True)),
                ('sender', models.EmailField(max_length=50, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ts'], name='main_regist_ts_2c07b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('relay_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tunnel', models.CharField(max_length=50, null=True)),
                ('tag', models.CharField(max_length=50, null=True)),
                ('properties', models.CharField(max_length=50, null=True)),
                ('port', models.IntegerField(default=5101)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relay_source', to='main.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relay_target', to='main.node')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('uuid', models.CharField(default=main.models.user_uuid, max_length=50, unique=True)),
                ('tag', models.CharField(max_length=15, null=True)),
                ('reg_time', models.IntegerField(default=main.models.current_unix)),
                ('last_activity', models.IntegerField(default=main.models.current_unix)),
                ('last_change', models.IntegerField(default=main.models.current_unix)),
                ('upload', models.BigIntegerField(default=0)),
                ('download', models.BigIntegerField(default=0)),
                ('balance', models.BigIntegerField(default=21474836480)),
                ('remarks', models.TextField(max_length=2048, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='main_user_email_6be720_idx'), models.Index(fields=['uuid'], name='main_user_uuid_e2f047_idx'), models.Index(fields=['last_change'], name='main_user_last_ch_f3f086_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('upload', models.BigIntegerField(default=0)),
                ('download', models.BigIntegerField(default=0)),
                ('ts', models.IntegerField(default=main.models.current_unix)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_traffic_log', to='main.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_traffic_log', to='main.user')),
            ],
            options={
                'indexes': [models.Index(fields=['ts'], name='main_traffi_ts_48a954_idx')],
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('ut_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('upload', models.BigIntegerField(default=0)),
                ('download', models.BigIntegerField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='node', to='main.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.user')),
            ],
            options={
                'indexes': [models.Index(fields=['node', 'user'], name='node_user'), models.Index(fields=['node', 'date'], name='node_date'), models.Index(fields=['node'], name='node'), models.Index(fields=['date'], name='date'), models.Index(fields=['node', 'user', 'date'], name='node_user_date')],
            },
        ),
        migrations.CreateModel(
            name='Sublog',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('ts', models.IntegerField(default=main.models.current_unix)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('remarks', models.CharField(max_length=45, null=True)),
                ('proxy_group', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sublog', to='main.user')),
            ],
            options={
                'indexes': [models.Index(fields=['ts'], name='main_sublog_ts_a183de_idx')],
            },
        ),
    ]
