# Generated by Django 5.0.9 on 2024-11-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='traffic',
            name='node_date',
        ),
        migrations.RemoveIndex(
            model_name='traffic',
            name='date',
        ),
        migrations.RemoveIndex(
            model_name='traffic',
            name='node_user_date',
        ),
        migrations.RenameField(
            model_name='traffic',
            old_name='date',
            new_name='ut_date',
        ),
        migrations.AddIndex(
            model_name='traffic',
            index=models.Index(fields=['node', 'ut_date'], name='node_date'),
        ),
        migrations.AddIndex(
            model_name='traffic',
            index=models.Index(fields=['ut_date'], name='date'),
        ),
        migrations.AddIndex(
            model_name='traffic',
            index=models.Index(fields=['node', 'user', 'ut_date'], name='node_user_date'),
        ),
    ]
