# Generated by Django 5.0.9 on 2024-11-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_traffic_node_date_remove_traffic_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['enabled'], name='main_user_enabled_728e07_idx'),
        ),
    ]
