# Generated by Django 5.0.9 on 2024-11-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_main_user_enabled_728e07_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
