# Generated by Django 5.0.9 on 2024-11-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_node_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='relay',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='idc',
            field=models.TextField(blank=True, default='Unknown', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='ipv4',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='node',
            name='ipv6',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv6'),
        ),
        migrations.AlterField(
            model_name='node',
            name='remarks',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='relay',
            name='properties',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='relay',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='relay',
            name='tunnel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='remarks',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
