# Generated by Django 5.0.9 on 2024-12-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mix_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='traffic_limit',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='traffic_refresh_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='node',
            name='properties',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='tag',
            field=models.CharField(default='gfw:c', max_length=50),
        ),
    ]
