# Generated by Django 5.0.9 on 2024-12-01 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_node_traffic_limit_node_traffic_refresh_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='traffic_refresh_day',
            new_name='traffic_reset_day',
        ),
    ]
