# Generated by Django 5.0.9 on 2024-12-03 02:13

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_last_rotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_rotation',
            field=models.IntegerField(default=main.models.current_unix, null=True),
        ),
    ]
