# Generated by Django 5.0.9 on 2024-12-09 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_user_last_rotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mix',
            name='scope',
            field=models.CharField(choices=[('edu', 'edu'), ('default', 'default')], default='edu', max_length=30),
        ),
        migrations.CreateModel(
            name='NodeTraffic',
            fields=[
                ('node_traffic_id', models.AutoField(primary_key=True, serialize=False)),
                ('ut_date', models.DateField()),
                ('upload', models.BigIntegerField(default=0)),
                ('download', models.BigIntegerField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.node')),
            ],
            options={
                'indexes': [models.Index(fields=['ut_date'], name='node_traffic_date'), models.Index(fields=['node'], name='node_traffic_node'), models.Index(fields=['node', 'ut_date'], name='node_traffic_node_date')],
            },
        ),
        migrations.CreateModel(
            name='UserTraffic',
            fields=[
                ('user_traffic_id', models.AutoField(primary_key=True, serialize=False)),
                ('ut_date', models.DateField()),
                ('upload', models.BigIntegerField(default=0)),
                ('download', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'indexes': [models.Index(fields=['ut_date'], name='user_traffic_date'), models.Index(fields=['user'], name='user_traffic_user'), models.Index(fields=['user', 'ut_date'], name='user_traffic_user_date')],
            },
        ),
    ]
