# Generated by Django 5.0.12 on 2025-02-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_mix_scope_nodetraffic_usertraffic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mix',
            name='scope',
            field=models.CharField(choices=[('default_view', 'default_view'), ('Jiaoyuwang', 'Jiaoyuwang'), ('Dianxin', 'Dianxin'), ('Yidong', 'Yidong'), ('Liantong', 'Liantong'), ('Liantong_Huabei', 'Liantong_Huabei'), ('Dianxin_Beijing', 'Dianxin_Beijing')], default='Jiaoyuwang', max_length=30),
        ),
        migrations.AlterField(
            model_name='node',
            name='traffic_reset_day',
            field=models.FloatField(default=1.0),
        ),
    ]
