# Generated by Django 5.0.9 on 2025-02-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_mix_scope_alter_node_traffic_reset_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='traffic_reset_day',
            field=models.IntegerField(default=1),
        ),
    ]
