# Generated by Django 5.0.13 on 2025-06-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_node_traffic_reset_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['blocked'], name='main_user_blocked_3e0780_idx'),
        ),
    ]
