# Generated by Django 5.0.13 on 2025-06-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_abuseevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abuseevent',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
